### ISSUE TITLE
No Log

### ISSUE THREAD

**Issue by alexynior28** [Technowlogy-Pushpender/technowlogger#19]
Hi,

*parrot-os

I have the following WARNING:

4603 WARNING: library user32 required via ctypes not found
4614 WARNING: library gdi32 required via ctypes not found
4629 WARNING: library shcore.dll required via ctypes not found

*The data is sent to the email but the log is empty.

**Comment by Technowlogy-Pushpender** [comment]
Can you send the screenshot of error

**Comment by Technowlogy-Pushpender** [comment]
Update your keylogger

And then specify --debug flag while creating payload, and read the debug
section of this documentation

**Comment by alexynior28** [comment]
Yes

`....
Successfully installed essential-generators-0.9.2
Invalid requirement: ''
Traceback (most recent call last):
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/requirements.py", line 95, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "''": Expected W:(abcd...)
`
![YDRAY-Captura-de-pantalla-2020-04-19-18-21-45](https://user-images.githubusercontent.com/19245743/79703425-67a4f280-8271-11ea-9c70-93ed9914f233.png)
![93930471_222286912361159_1059123048109572096_n](https://user-images.githubusercontent.com/19245743/79703430-6ecc0080-8271-11ea-9370-76dc483acd92.png)

So I installed it manually. Row by row of the installer_linux.sh file. However, I don't get the logs in the email...

thanks for your attention

**Comment by Technowlogy-Pushpender** [comment]
Are you making payload for windows or Linux, if you are making payload for
windows

Then create a payload with --debug flag, this will make payload to run on
foreground with cmd

And will show your proper execution error so that it can be fixed

Send the screenshot of that cmd error of payload (make sure to run payload
through cmd,not by double clicking)

**Comment by alexynior28** [comment]
Hi, I'm creating it for Linux. Should I run it some other way?

**Comment by Technowlogy-Pushpender** [comment]
Sorry For Late Reply! I have just updated the Keylogger.py File

Just Update your Technowlogger and run Keylogger.py like this
```
python3 Keylogger.py
``
Now  keylogger module can be executed standalone, test the Keylogger.py without compiling it, 

If you get any error, please let me know

**Comment by alexynior28** [comment]
Hi, I tried it on Windows (Python3.8) and everything looks fine. The svchost file is in the Roaming folder and also in the registry (...Run). In the mail it comes to me:

Logs:
** TechNowlogger started on Windows System **

And I also get the first capture in the mail.

But then from then on, it doesn't capture anything. I don't get any more log emails :s

**Comment by Technowlogy-Pushpender** [comment]
Make new exe with --debug flag

**Comment by Technowlogy-Pushpender** [comment]
And then run the exe from command prompt, it will show you the error which
it might be encountering
