### ISSUE TITLE
subprocess.CalledProcessError: Command 'where python' returned non-zero exit status 127. 

### ISSUE THREAD

**Issue by ricko2991** [Technowlogy-Pushpender/technowlogger#25]
Hi can you help me. when i run python3 technowgen.py -e anonymus@gmail.com -p 12345678 -w -o virus.exe --icon icon/pdf.ico on kali machine. give me error message below:

/bin/sh: 1: where: not found                                                                                                                                          
Traceback (most recent call last):                                                                                                                                    
  File "technowgen.py", line 276, in <module>                                                                                                                         
    WINDOWS_PYTHON_PYINSTALLER_PATH = get_python_pyinstaller_path()                                                                                                   
  File "technowgen.py", line 41, in get_python_pyinstaller_path                                                                                                       
    python_path = subprocess.check_output("where python", shell=True)                                                                                                 
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output                                                                                                  
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                  
  File "/usr/lib/python3.8/subprocess.py", line 512, in run                                                                                                           
    raise CalledProcessError(retcode, process.args,                                                                                                                   
subprocess.CalledProcessError: Command 'where python' returned non-zero exit status 127.

**Comment by Technowlogy-Pushpender** [comment]
Please Check It Now!

**Comment by ricko2991** [comment]
yeah, i have some error to. i can't install win32gui on wine python 3.7

**Comment by Technowlogy-Pushpender** [comment]
Please google that particular error, and try to solve it,

If you are unable to create payload for windows from Linux, then you can
install technowhorse on windows for windows payload creation.

And in order to create Linux payload, you can simply create it from your
Linux system

**Comment by ricko2991** [comment]
Ok. I've tried to make it in windows. and it installs the package fine without any errors. Thanks a lot.
